import {Item, MapData} from '@/types/game';

export const defaultMaps = {
  exterior: {
    groundLayer: [
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
    ],
    startPosition: { x: 8, y: 8 },
    zonePositions: [
      {name: 'zone1', destination: 'zone1', x: 4, y: 4 },
      {name: 'zone2', destination: 'zone2', x: 11, y: 4 },
      {name: 'zone3', destination: 'zone3', x: 4, y: 10 },
    ]
  } as MapData,
  zone1: {
    groundLayer: [
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
    ],
    zonePositions: [
      {name: 'zone1', destination: 'exterior', x: 10, y: 5 },
    ],
    startPosition: { x: 10, y: 5 }
  } as MapData,
  zone2: {
    groundLayer: [
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
    ],
    zonePositions: [
      {name: 'zone2', destination: 'exterior', x: 4, y: 4 },
    ],
    startPosition: { x: 4, y: 4 }
  } as MapData,
  zone3: {
    groundLayer: [
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'floor', tileId: 0 }, { type: 'wall', tileId: 1 }],
      [{ type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }, { type: 'wall', tileId: 1 }],
    ],
    zonePositions: [
      {name: 'zone3', destination: 'exterior', x: 4, y: 5 },
    ],
    startPosition: { x: 4, y: 5 }
  } as MapData
};